name: Build and Deploy Wedgo Backend Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              id: checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Set up Docker Buildx
              id: setup_buildx
              uses: docker/setup-buildx-action@v3

            - name: Install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            - name: Login to Harbor
              id: login_harbor
              env:
                  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
              run: echo $HARBOR_PASSWORD | docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

            - name: Set environment variables
              run: |
                  echo "TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
                  echo "HARBOR_IMAGE=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT_BACKEND }}/wedgobackend" >> $GITHUB_ENV

            - name: Build Docker images
              id: build_docker_images
              run: |
                  cat <<EOF > .env
                  PORT=${{ secrets.DEV_PORT }}
                  DB_USER=${{ secrets.DEV_DB_USER }}
                  DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
                  DB_HOST=${{ secrets.DEV_DB_HOST }}
                  DB_PORT=${{ secrets.DEV_DB_PORT }}
                  DB_NAME=${{ secrets.DEV_DB_NAME }}
                  ACCESS_TOKEN_SECRET=${{ secrets.DEV_ACCESS_TOKEN_SECRET }}
                  REFRESH_TOKEN_SECRET=${{ secrets.DEV_REFRESH_TOKEN_SECRET }}
                  FRONTEND_URL=${{ secrets.DEV_FRONTEND_URL }}
                  MINIO_ENDPOINT=${{ secrets.DEV_MINIO_ENDPOINT }}
                  MINIO_PORT=${{ secrets.DEV_MINIO_PORT }}
                  MINIO_USE_SSL=${{ secrets.DEV_MINIO_USE_SSL }}
                  MINIO_ACCESS_KEY=${{ secrets.DEV_MINIO_ACCESS_KEY }}
                  MINIO_SECRET_KEY=${{ secrets.DEV_MINIO_SECRET_KEY }}
                  MINIO_BUCKET=${{ secrets.DEV_MINIO_BUCKET }}
                  MSG91_AUTH_KEY=${{ secrets.DEV_MSG91_AUTH_KEY }}
                  MSG91_TEMPLATE_ID=${{ secrets.DEV_MSG91_TEMPLATE_ID }}
                  FIREBASE_PROJECT_ID=${{ secrets.DEV_FIREBASE_PROJECT_ID }}
                  FIREBASE_CLIENT_EMAIL=${{ secrets.DEV_FIREBASE_CLIENT_EMAIL }}
                  FIREBASE_PRIVATE_KEY="${{ secrets.DEV_FIREBASE_PRIVATE_KEY }}"
                  HARBOR_URL=${{ secrets.HARBOR_URL }}
                  HARBOR_PASSWORD=${{ secrets.HARBOR_PASSWORD }}
                  HARBOR_USERNAME=${{ secrets.HARBOR_USERNAME }}
                  HARBOR_PROJECT=${{ secrets.HARBOR_PROJECT_BACKEND }}
                  TAG=${{env.TAG}}
                  EOF
                  echo "Building with TAG: ${{ env.TAG }}"
                  echo "Image: $HARBOR_URL/$HARBOR_PROJECT/wedgobackend:${{ env.TAG }}"
                  docker-compose -f docker-compose.yml build \
                    --build-arg TAG=${{ env.TAG }}
              env:
                  HARBOR_URL: ${{ secrets.HARBOR_URL }}
                  HARBOR_PROJECT: ${{ secrets.HARBOR_PROJECT_BACKEND }}
                  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
                  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
                  TAG: ${{ env.TAG }}

            - name: Verify Docker image
              id: verify_docker_image
              run: docker images ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT_BACKEND }}/wedgobackend:${TAG}
              env:
                  TAG: ${{ env.TAG }}

            - name: Cache Trivy DB
              uses: actions/cache@v5
              with:
                  path: ~/.cache/trivy
                  key: ${{ runner.os }}-trivy-db
                  restore-keys: |
                      ${{ runner.os }}-trivy-db

            - name: Trivy Scan Docker images
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT_BACKEND }}/wedgobackend:${{env.TAG}}
              timeout-minutes: 30

            - name: Push Docker images
              id: push_docker_images
              run: |
                  docker-compose -f docker-compose.yml push
              env:
                  HARBOR_URL: ${{ secrets.HARBOR_URL }}
                  HARBOR_PROJECT: ${{ secrets.HARBOR_PROJECT_BACKEND }}
                  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
                  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
                  TAG: ${{ env.TAG }}

            # CD steps for auto deployment
            - name: Checkout GitOps repository
              uses: actions/checkout@v5
              with:
                  repository: healthligence-s/healthligence-infra
                  ref: main
                  token: ${{ secrets.GITOPS_TOKEN }}
                  path: healthligence-infra

            - name: Update Kubernetes manifests
              run: |
                  cd healthligence-infra/wedgo/wedgo-backend

                  # Configure Git
                  git config --global user.email "${{ secrets.GITOPS_EMAIL }}"
                  git config --global user.name "${{ secrets.GITOPS_USERNAME }}"

                  # Update only the image tag in the Deployment
                  sed -i "s+${{ secrets.HARBOR_URL }}/wedgo/wedgobackend:.*+${{ secrets.HARBOR_URL }}/wedgo/wedgobackend:${TAG}+g" wedgo-backend.yaml

                  # Commit and push changes
                  git add wedgo-backend.yaml
                  git commit -m "chore: Update wedgo backend image tag to ${TAG}"
                  git push origin main
              env:
                  TAG: ${{ env.TAG }}

            - name: Cleanup GitOps repository
              if: always()
              run: |
                  rm -rf healthligence-infra

            - name: Logout from Harbor
              id: logout_harbor
              run: docker logout ${{ secrets.HARBOR_URL }}
